version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - auth-service
      - user-service
      - bus-service
      - location-service
      - chat-service
      - notification-service
      - file-service

  # Auth Service
  auth-service:
    build: ./backend/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=this_is_top_secret_jimbo
      - REDIS_URL=redis://redis:6379
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongo
      - redis

  # User Service
  user-service:
    build: ./backend/user-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/userdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  # Bus Service
  bus-service:
    build: ./backend/bus-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/busdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  # Location Service
  location-service:
    build: ./backend/location-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - MONGO_URI=mongodb://mongo:27017/locationdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  # Chat Service
  chat-service:
    build: ./backend/chat-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - MONGO_URI=mongodb://mongo:27017/chatdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  # Notification Service
  notification-service:
    build: ./backend/notification-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - MONGO_URI=mongodb://mongo:27017/notificationdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  # File Service
  file-service:
    build: ./backend/file-service
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
      - MONGO_URI=mongodb://mongo:27017/filedb
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
      - redis

  # MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  # Redis for message broker
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
